### ISSUE TITLE
Allow computed property keys so the cache invalidates

### ISSUE THREAD

**Issue by cursedquail** [rmmmp/ember-computed-query#3]
I think this would be a pretty simple change. Change the computed to something like

```js
export function query(modelName, ...keys, options = {}) {
  return computed(...keys, {
    get() {
      const query = typeof options === 'function' ? options(this) : options;
      const PromiseArray = ArrayProxy.extend(PromiseProxyMixin);

      return PromiseArray.create({
        promise: this.get('store').query(modelName, query),
      });
    },
  }).readOnly();
}
```

**Comment by mikkopaderes** [comment]
You're right. I might just move the `...keys` after the `options` since it can be optional. I'll do this tomorrow. Thanks!

**Comment by cursedquail** [comment]
I _believe_ (I'm not at a computer atm so can't validate this) that if you only provide two parameters then only `modelName` and `options` will be set and `keys` will be `[]`.

Again, I'm not 100% on that, but it'd be worth checking at least?

**Comment by mikkopaderes** [comment]
@NLincoln, you can't have another param after a rest param.
