### ISSUE TITLE
Going forward

### ISSUE THREAD

**Issue by Exelord** [rmmmp/ember-computed-query#4]
Hey!
Take a look at my project https://exelord.github.io/ember-custom-actions/
Maybe you will find some inspiration and ideas how to make it even better :)
Cheers

**Comment by mikkopaderes** [comment]
@Exelord, your project looks neat but I don't have any use-case around it for myself that I could suggest to improve it or something to adopt in this addon.

Closing this. Feel free to re-open if you have something to add. :grin:
